/* 
   Search.vue
*/

const names = [
   'Aatrox',
   'Ahri',
   'Akali',
   'Akshan',
   'Alistar',
   'Amumu',
   'Anivia',
   'Annie',
   'Aphelios',
   'Ashe',
   'AurelionSol',
   'Azir',
   'Bard',
   'Belveth',
   'Blitzcrank',
   'Brand',
   'Braum',
   'Briar',
   'Caitlyn',
   'Camille',
   'Cassiopeia',
   'Chogath',
   'Corki',
   'Darius',
   'Diana',
   'DrMundo',
   'Draven',
   'Ekko',
   'Elise',
   'Evelynn',
   'Ezreal',
   'Fiddlesticks',
   'Fiora',
   'Fizz',
   'Galio',
   'Gangplank',
   'Garen',
   'Gnar',
   'Gragas',
   'Graves',
   'Gwen',
   'Hecarim',
   'Heimerdinger',
   'Illaoi',
   'Irelia',
   'Ivern',
   'Janna',
   'JarvanIV',
   'Jax',
   'Jayce',
   'Jhin',
   'Jinx',
   'KSante',
   'Kaisa',
   'Kalista',
   'Karma',
   'Karthus',
   'Kassadin',
   'Katarina',
   'Kayle',
   'Kayn',
   'Kennen',
   'Khazix',
   'Kindred',
   'Kled',
   'KogMaw',
   'Leblanc',
   'LeeSin',
   'Leona',
   'Lillia',
   'Lissandra',
   'Lucian',
   'Lulu',
   'Lux',
   'Malphite',
   'Malzahar',
   'Maokai',
   'MasterYi',
   'Milio',
   'MissFortune',
   'MonkeyKing',
   'Mordekaiser',
   'Morgana',
   'Naafiri',
   'Nami',
   'Nasus',
   'Nautilus',
   'Neeko',
   'Nidalee',
   'Nilah',
   'Nocturne',
   'Nunu',
   'Olaf',
   'Orianna',
   'Ornn',
   'Pantheon',
   'Poppy',
   'Pyke',
   'Qiyana',
   'Quinn',
   'Rakan',
   'Rammus',
   'RekSai',
   'Rell',
   'Renata',
   'Renekton',
   'Rengar',
   'Riven',
   'Rumble',
   'Ryze',
   'Samira',
   'Sejuani',
   'Senna',
   'Seraphine',
   'Sett',
   'Shaco',
   'Shen',
   'Shyvana',
   'Singed',
   'Sion',
   'Sivir',
   'Skarner',
   'Sona',
   'Soraka',
   'Swain',
   'Sylas',
   'Syndra',
   'TahmKench',
   'Taliyah',
   'Talon',
   'Taric',
   'Teemo',
   'Thresh',
   'Tristana',
   'Trundle',
   'Tryndamere',
   'TwistedFate',
   'Twitch',
   'Udyr',
   'Urgot',
   'Varus',
   'Vayne',
   'Veigar',
   'Velkoz',
   'Vex',
   'Vi',
   'Viego',
   'Viktor',
   'Vladimir',
   'Volibear',
   'Warwick',
   'Xayah',
   'Xerath',
   'XinZhao',
   'Yasuo',
   'Yone',
   'Yorick',
   'Yuumi',
   'Zac',
   'Zed',
   'Zeri',
   'Ziggs',
   'Zilean',
   'Zoe',
   'Zyra',
]

const table = {
   'AurelionSol' : 'Aurelion Sol',
   'Belveth' : "Bel'Veth",
   'Chogath' : "Cho'Gath",
   'DrMundo' : 'Dr. Mundo',
   // 'FiddleSticks' : 'Fiddlesticks',
   'JarvanIV' : 'Jarvan IV',
   "KSante" : "K'Sante",
   "Kaisa" : "Kai'Sa",
   'Khazix' : "Kha'Zix",
   'KogMaw' : "Kog'Maw",
   'Leblanc' : 'LeBlanc',
   'LeeSin' : 'Lee Sin',
   'MasterYi' : 'Master Yi',
   'MissFortune' : 'Miss Fortune',
   'MonkeyKing' : 'Wukong',
   'Nunu' : 'Nunu & Willump',
   'RekSai' : "Rek'Sai",
   'Renata' : 'Renata Glasc',
   'TahmKench' : 'Tahm Kench',
   'TwistedFate' : 'Twisted Fate',
   'Velkoz' : "Vel'Koz",
   'XinZhao' : 'Xin Zhao'
}

export default {
   names,
   table
}